version: 2
jobs:
    build:
        working_directory: feedback_api
    docker:
        - image: circleci/ruby:2.4.1
        environment:
            RAILS_ENV: test
    steps:
        - checkout
        # Setup the database
        - run: bundle exec rake db:setup

        # Run the tests
        - run: bundle exec rake

      