version: 2
jobs:
    build:
        working_directory: Feedbackapp_test
        docker:
            - image: circleci/ruby:2.4.1
              environment:
                RAILS_ENV: test
    steps:
        - checkout
      - run: cp .sample.env .env
      - run: bundle exec rake